ServiceTeam/ServiceTeam/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import views
from ServiceTeam import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('clock_card/', include('clock_card.urls', namespace='clock_details')),
    path('time_sheets/', include('time_sheets.urls', namespace='time_sheets')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ServiceTeam/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('newuser', views.newuser, name='newuser'),
    path('users/', views.UserListView.as_view(), name='user_list'),
    path('user_update/<int:pk>', views.UserUpdateView.as_view(), name='user_update'),
    path('profile_update/<int:pk>', views.UserProfileInfoUpdateView.as_view(), name='profile_update'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='accounts/password_change.html'), name='password_change'),
    path('password_change/done/', views.password_change_done, name='password_change_done'),
]

ServiceTeam/clock_card/urls.py
from django.urls import path
from clock_card import views

app_name = 'clock_card'

urlpatterns = [
    path('clock', views.MyClockCardList.as_view(), name='clock'),
    path('clock_entry', views.ClockEventCreateView.as_view(), name='clock_entry')
]

ServiceTeam/time_sheets/urls.py
from django.urls import path
from time_sheets import views

app_name = 'time_sheets'

urlpatterns = [
    path('team', views.TeamListView.as_view(), name='teamlist')
]

ServiceTeam/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static "CSS/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "CSS/mystyle.css" %}">
    <script src="{% static "JS/jquery-3.3.1.js" %}"></script>
    <script src="{% static "JS/bootstrap.min.js" %}"></script>
    <title>TEAM APP</title>
  </head>
  <body id="myBody" onload="" >
  <nav id="topnav" class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a id="leftMenuItems" class="navbar-brand" href="{% url 'home' %}">Dimako Service Team</a>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
          {% if user.is_authenticated %}
            <li id="ledeMenu"><a id="leftMenuItems" href="{% url 'accounts:user_list' %}">TEAM MEMBERS</a></li>
            <li id="clockMenu"><a id="leftMenuItems" href="{% url 'clock_card:clock' %}">CLOCK CARD</a></li>
              {% if perms.auth.can_reg_usr %}
              <li id="timeSheetMenu"><a id="leftMenuItems" href="{% url 'time_sheets:teamlist' %}">TIME SHEETS</a></li>
              <li id="registerMenu"><a id="leftMenuItems" href="{% url 'accounts:newuser' %}">REGISTER</a></li>
              {% endif %}
              {% if perms.auth.add_permission %}
              <li id="registerMenu"><a id="leftMenuItems" href="{% url 'admin:index' %}">ADMIN</a></li>
              {% endif %}
          {% endif %}
        </ul>
        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
          <li>
            <div id="leftMenuItems" class="search-container">
            </div>
          </li>
          <li><a id="leftMenuItems" href="{% url 'accounts:logout' %}"><span class="glyphicon glyphicon-user"></span></a></li>
          <li><a id="userID">{{ user }}</a>
          {% else %}
            <li id="tekenMenu"><a id="leftMenuItems" href="{% url 'accounts:login' %}"><span class="glyphicon glyphicon-user"></span></a></li>
          {% endif %}
        </ul>
      </div>
    </div>
</nav>
    <div class="container" style="margin-top:60px">
      {% block body_block %}
      <!-- Anything ouside of this will be inherited if you extend -->
      {% endblock %}
    </div>
  </body>
</html>

ServiceTeam/templates/index.html
{% extends "base.html" %}
  {% load staticfiles %}
  {% block body_block %}
  <div class="container">
    <div class="jumbotron" id="myjumbotron">
      <h2>Welcome To The Service Team Web-App</h2>
      <h4>Please Login to use the App.</h4>
    </div>
  </div>
  {% endblock %}