ServiceTeam/ServiceTeam/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import views
from ServiceTeam import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('clock_card/', include('clock_card.urls', namespace='clock_details')),
    path('time_sheets/', include('time_sheets.urls', namespace='time_sheets')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ServiceTeam/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('newuser', views.newuser, name='newuser'),
    path('users/', views.UserListView.as_view(), name='user_list'),
    path('user_update/<int:pk>', views.UserUpdateView.as_view(), name='user_update'),
    path('profile_update/<int:pk>', views.UserProfileInfoUpdateView.as_view(), name='profile_update'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='accounts/password_change.html'), name='password_change'),
    path('password_change/done/', views.password_change_done, name='password_change_done'),
]

ServiceTeam/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib import auth
from PIL import Image as Img
from PIL import ExifTags
from io import BytesIO
from django.core.files import File


class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, related_name="main_user", on_delete=models.CASCADE)

    # additional
    job_title = models.CharField(blank=True, max_length=100)
    department = models.CharField(blank=True, max_length=100)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
    employee_no = models.CharField(max_length=256, blank=True, null=True)
    cell_phone = models.CharField(max_length=256, blank=True, null=True)

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        try:
            if self.profile_pic:
                pilImage = Img.open(BytesIO(self.profile_pic.read()))
                for orientation in ExifTags.TAGS.keys():
                    if ExifTags.TAGS[orientation] == 'Orientation':
                        break
                exif = dict(pilImage._getexif().items())

                if exif[orientation] == 3:
                    pilImage = pilImage.rotate(180, expand=True)
                elif exif[orientation] == 6:
                    pilImage = pilImage.rotate(270, expand=True)
                elif exif[orientation] == 8:
                    pilImage = pilImage.rotate(90, expand=True)

                output = BytesIO()
                pilImage.save(output, format='JPEG', quality=75)
                output.seek(0)
                self.profile_pic = File(output, self.profile_pic.name)

            return super(UserProfileInfo, self).save(*args, **kwargs)
        except:
            return super(UserProfileInfo, self).save(*args, **kwargs)

ServiceTeam/accounts/forms.py
from django import forms
from accounts.models import UserProfileInfo
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):

    class Meta():
        model = UserProfileInfo
        fields = ('profile_pic', 'employee_no', 'cell_phone', 'job_title', 'department')

ServiceTeam/accounts/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.models import Permission, User
from django.contrib.auth import authenticate,login,logout
from accounts.forms import UserForm, UserProfileInfoForm
from . import forms
from . import models


def newuser(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'accounts/newuser.html', {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})



## Users View
class UserListView(ListView):
    context_object_name = 'club_users'
    model = models.UserProfileInfo

class UserUpdateView(UpdateView):
    fields = ('username', 'first_name', 'last_name', 'email')
    model = models.User
    success_url = reverse_lazy('accounts:user_list')

class UserProfileInfoUpdateView(UpdateView):
    fields = ('profile_pic', 'cell_phone')
    model = models.UserProfileInfo
    success_url = reverse_lazy('accounts:user_list')

def password_change_done(request):
    return render(request, 'accounts/password_change_done.html')

ServiceTeam/accounts/templates/accounts/login.html
{% extends "base.html" %}
  {% load staticfiles %}
  {% block body_block %}
  <div class="container">
    <div class="jumbotron" id="myjumbotron">
      <form method="POST">
      {% csrf_token %}
      <p id="registrationform">User Name: <input type="text" name="username" placeholder="Enter Username"></p>
      <p id="registrationform">Password: <input type="password" name="password"></p>
      <input type="submit" class="btn btn-primary" value="Login">
      <!-- <input type="hidden" name="next" value="{{ next }}"> -->
    </form>
    </div>
  </div>
  <script src="{% static "JS/login.js" %}"></script>
  {% endblock %}

ServiceTeam/accounts/templates/accounts/newuser.html
<!DOCTYPE html>
{% extends "base.html" %}
  {% load staticfiles %}
  {% block body_block %}
  <div class="container">
    <div class="jumbotron" id="myjumbotron">
      {% if registered %}
    <h2>Thank you, user registration complete!</h2>
    <p>Please signin with your Username and password.</p>
  {% else %}
    <h2>Please register a user here!</h2>
    <h4>Complete the following form:</h4>
    <form id="myform" enctype="multipart/form-data" method="POST">
      {% csrf_token %}
      <p id="registrationform">Username: {{user_form.username}}</p>
      <p id="registrationform">Name: {{user_form.first_name}}</p>
      <p id="registrationform">Surname: {{user_form.last_name}}</p>
      <p id="registrationform">Email: {{user_form.email}}</p>
      <p id="registrationform">Password: {{user_form.password}}</p>
      <p id="registrationform">Employee Number: {{profile_form.employee_no}}</p>
      <p id="registrationform">Job Title: {{profile_form.job_title}}</p>
      <p id="registrationform">Department: {{profile_form.department}}</p>
      <p id="registrationform">Cell Phone Number: {{profile_form.cell_phone}}</p>
      <p id="registrationform">Photo(Optional): {{profile_form.profile_pic}}</p>
      <input type="submit" class="btn btn-primary" value="Register">
    </form>
  {% endif %}
    </div>
  </div>
  <script>
    $("#registerMenu").css("background-color", "rgba(48, 150, 150, .95)");
  </script>
  {% endblock %}

ServiceTeam/accounts/templates/accounts/password_change.html
<!DOCTYPE html>
{% extends "base.html" %}
  {% load staticfiles %}
  {% block body_block %}
  <div class="container">
    <div class="jumbotron" id="myjumbotron">
      <form action="{% url 'password_change' %}" method="POST">
      {% csrf_token %}
      <p id="registrationform">Old Password: <input type="password" name="old_password"></p>
      <p id="registrationform">New Password: <input type="password" name="new_password1"></p>
      <ul>
        <li>Your password may not contain any personal information.</li>
        <li>Must be longer than 8 characters.</li>
        <li>Can not contain just numbers.</li>
        <li>Can not be a common password ex. - password</li>
      </ul>
      <p id="registrationform">Repeat Password: <input type="password" name="new_password2"></p>
      <p><input type="submit" class="btn btn-danger" value="Submit Change"></p>
      <a href="{% url 'accounts:user_list' %}" class="btn btn-primary glyphicon glyphicon-step-backward" role="button"> Cancel</a>
    </form>
    </div>
  </div>
  <script src="{% static "JS/login.js" %}"></script>
  {% endblock %}

ServiceTeam/accounts/templates/accounts/password_change_done.html
{% extends "base.html" %}
  {% load staticfiles %}
  {% block body_block %}
  <div class="container">
    <div class="jumbotron" id="myjumbotron">
      <h3>Thank you, your password is changed!</h3>
    </div>
  </div>
  <script src="{% static "JS/login.js" %}"></script>
  {% endblock %}

ServiceTeam/accounts/templates/accounts/signup.html
{% extends "base.html" %}
  {% load staticfiles %}
  {% block body_block %}
  <div class="container">
    <div class="jumbotron" id="myjumbotron">
      <form method="POST">
      {% csrf_token %}
      <p id="registrationform">Kubernaam: {{form.username}}</p>
      <p id="registrationform">Naam: {{form.first_name}}</p>
      <p id="registrationform">Van: {{form.last_name}}</p>
      <p id="registrationform">e-pos: {{form.email}}</p>
      <p id="registrationform">Wagwoord: {{form.password1}}</p>
      <ul>
        <li>Jou wagwoord mag nie van jou pesoonlike inligting bevat nie.</li>
        <li>Moet 8 karakters of langer wees.</li>
        <li>Mag nie net uit nommers bestaan nie.</li>
        <li>Mag nie 'n algemene wagwoord wees nie. bv. - password</li>
      </ul>
      <p id="registrationform">Herhaal wagwoord: {{form.password2}}</p>
      <input type="submit" class="btn btn-primary" value="Registreer">
    </form>
    </div>
  </div>
  <script>
    $("#registerMenu").css("background-color", "rgba(48, 150, 150, .95)");
  </script>
  {% endblock %}

ServiceTeam/accounts/templates/accounts/signup_done.html
{% extends "base.html" %}
  {% load staticfiles %}
  {% block body_block %}
  <div class="container">
    <div class="jumbotron" id="myjumbotron">
      <h3>Baie dankie, jy is nou geregistreer!</h3>
    </form>
    </div>
  </div>
  <script src="{% static "JS/login.js" %}"></script>
  {% endblock %}

ServiceTeam/accounts/templates/accounts/userprofileinfo_form.html
{% extends "base.html" %}
  {% load staticfiles %}
  {% block body_block %}
  <div class="container">
    <div class="jumbotron" id="myjumbotron">
      <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        <p id="registrationform">Profile Photo: {{form.profile_pic}}</p>
        <p id="registrationform">Cell Phone: {{form.cell_phone}}</p>
        <input type="submit" class="btn btn-warning" value="Update">
        <a href="{% url 'accounts:user_list' %}" class="btn btn-primary glyphicon glyphicon-step-backward" role="button"> Cancel</a>
      </form>
    </div>
  </div>
  <script src="{% static "JS/lede.js" %}"></script>
  {% endblock %}

ServiceTeam/accounts/templates/accounts/userprofileinfo_list.html
{% extends "base.html" %}
  {% load staticfiles %}
  {% block body_block %}
  <div class="container">
    <div class="jumbotron" id="myjumbotron">
      {% for lede in club_users %}
        {% if user.username == lede.user.username %}
          {% if lede.profile_pic %}
            <img src="{{ lede.profile_pic.url }}" alt="no image" width="100" height="100">
          {% else %}
            <p>No Photo!</p>
          {% endif %}
          <p id="registrationform">Employee Number: {{lede.employee_no}}</p>
          <p id="registrationform">Name: {{lede.user.first_name}}</p>
          <p id="registrationform">Surname: {{lede.user.last_name}}</p>
          <p id="registrationform">Job Title: {{ lede.job_title }}</p>
          <p id="registrationform">Department: {{ lede.department }}</p>
          <p id="registrationform">Email: {{lede.user.email}}</p>
          <p id="registrationform">Cell Phone: {{lede.cell_phone}}</p>
          <p></p>
          <p><a href="{% url 'accounts:user_update' pk=lede.user_id %}" class="btn btn-warning glyphicon glyphicon-edit" role="button"> Update</a></p>
          <p><a href="{% url 'accounts:profile_update' pk=lede.pk %}" class="btn btn-primary glyphicon glyphicon-picture" role="button"> Pesonal</a></p>
          <p><a href="{% url 'password_change' %}" class="btn btn-danger glyphicon glyphicon-sunglasses" role="button"> Change Password</a></p>
          <hr>
        {% endif %}
      {% endfor %}
    {% for lede in club_users %}
      {% if user.username != lede.user.username %}
        {% if lede.profile_pic %}
          <img src="{{ lede.profile_pic.url }}" alt="no image" width="100" height="100">
        {% else %}
          <p>No Photo!</p>
        {% endif %}
        <p id="registrationform">Employee Number: {{lede.employee_no}}</p>
        <p id="registrationform">Name: {{lede.user.first_name}}</p>
        <p id="registrationform">Surname: {{lede.user.last_name}}</p>
        <p id="registrationform">Job Title: {{ lede.job_title }}</p>
        <p id="registrationform">Department: {{ lede.department }}</p>
        <p id="registrationform">Email: {{lede.user.email}}</p>
        <p id="registrationform">Cell Phone: {{lede.cell_phone}}</p>
        <p></p>
        <hr>
      {% endif %}
    {% endfor %}
    </div>
  </div>
  <script src="{% static "JS/lede.js" %}"></script>
  {% endblock %}